{% set name = "napari-bbox" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-bbox-{{ version }}.tar.gz
  sha256: ac0eb416408eae837f49b1b1fc6d0c986af4c8d57c8f873409e518dcb8b3cc11

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - magicgui
    - napari <0.4.18
    - npe2
    - numpy
    - packaging
    - pandas
    - python >={{ python_min }},<3.11
    - qtpy
    - vispy

test:
  imports:
    - napari_bbox
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-bbox
  summary: A new layer for bounding boxes in 2+ dimensions
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/bauerdavid/napari-bbox

extra:
  recipe-maintainers:
    - bauerdavid
    - goanpeca
    - jaimergp
